language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools hexo-cli

script:
  - hexo generate

after_success:
  - firebase deploy --token=$FIREBASE_TOKEN
