language: rust
cache: cargo
sudo: false

branches:
  only:
    - master

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 10

before_script:
  - npm install -g firebase-tools 
  # Check if the mdbook binary exists before compiling it
  - which mdbook || cargo install --version 0.1.8 --force mdbook

script:
  # Clean the cargo directory (? maybe this will fix caching issues)
  - cargo clean
  # Pull dependencies for mdbook test
  - cargo test --release
  # Use prebuilt dependencies when running mdbook test
  - mdbook test -L target/release/deps
  # Finally, build the site.
  - mdbook build

after_success:
  - firebase deploy --token=$FIREBASE_TOKEN
