language: rust
cache: cargo
sudo: false

branches:
  only:
    - master

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 10

before_script:
  - npm install -g firebase-tools 
  # Check if the mdbook binary exists before compiling it
  - which mdbook || cargo install mdbook

script:
  - mdbook build

after_success:
  - firebase deploy --token=$FIREBASE_TOKEN
